[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  VITE_TMDB_API_KEY = "10069c04fb7414dd0a7683abb054c50b"
  VITE_TMDB_BASE_URL = "https://api.themoviedb.org/3"
  VITE_TMDB_IMAGE_BASE_URL = "https://image.tmdb.org/t/p"
